### PR TITLE
fix: modify middleware spell

### PR DESCRIPTION
**Pull request by lidianhao123**
##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change
Modify middleware spell

- any feature?
- close https://github.com/umijs/umi/ISSUE_URL

-----
[View rendered docs/plugins/api.md](https://github.com/lidianhao123/umi/blob/master/docs/plugins/api.md)
[View rendered docs/plugins/api.zh-CN.md](https://github.com/lidianhao123/umi/blob/master/docs/plugins/api.zh-CN.md)

### CODE REVIEW

**Comment by sorrycc** [comment]
是个问题，但这样改就不兼容了，dev.ts 和 registerMethods.ts  里需要兼容两种写法。

**Comment by lidianhao123** [comment]
1. 建议使用正确的拼写，大佬把PR合入
2. 暂时不知道如何实现兼容两种写法

**Comment by ycjcl868** [comment]
😂

**Comment by ycjcl868** [comment]
再注册一个旧的，然后 报个 warning

**Comment by ycjcl868** [comment]
如果要改，建议放到下个 minor 版本，umi 3.2

**Pull request closed without merging**
