### PR TITLE
feat: upgrade react-router to 5

### LINKED ISSUE #3475: ant pro内置的umi路由所依赖的react-router版本需要更新
现在用不了Hooks，useParams之类的

https://reacttraining.com/react-router/web/example/url-params

### PR DESCRIPTION
**Pull request by sorrycc**
Close #3475.

##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/umi/ISSUE_URL

### CODE REVIEW

**Comment by sorrycc** [comment]
ssr 的用例挂了， @ycjcl868 有空看下。

**Comment by ycjcl868** [comment]
ci 等 https://github.com/umijs/umi/pull/3447 merge 后再改

**Comment by ycjcl868** [comment]
SSR 测试没问题

**Comment by fjc0k** [comment]
请求发版。  🤓

**Comment by sorrycc** [comment]
@fjc0k 明天。

**Pull request merged**
