### PR TITLE
fix: workaround to resolve core-js path error bug

### LINKED ISSUE #5715: [Bug] 通过cnpm下载v2版本，为啥依赖的corejs下载的是v3.7.0的版本了？最近很多老项目编译都有问题了
最近通过cnpm 下载umi v2的版本 ，但是里面的core-js会依赖下载3.7.0的版本，这个是在哪里配置了么，v2的版本应该用core-js v2的版本才行，不然编译会爆错，这个是cnpm源导致？

### PR DESCRIPTION
**Pull request by PeachScript**
##### Checklist

- [x] `npm test` passes
- [x] commit message follows commit guidelines

##### Description of change

Process require statements in core-js lock plugin, but the real reason that caused the import statements transform to require statements still not found.

- close #5715

### CODE REVIEW

**Review by sorrycc — APPROVED** [review]
还是得找到根源，谁改的 import -> require 。

**Comment by PeachScript** [comment]
> 还是得找到根源，谁改的 import -> require 。

是的，主要现在答疑人数激增，先把问题 workaround 掉，我们在持续排查

**Comment by afc163** [comment]
看看 https://github.com/babel/babel/pull/12340/ 有没有关系？

**Comment by ycjcl868** [comment]
> 看看 [babel/babel#12340](https://github.com/babel/babel/pull/12340) 有没有关系？

可能相关

umi 的复现 demo： https://github.com/ycjcl868/umi-2-core-js-bug

**Comment by ycjcl868** [comment]
确认了，是这一行导致 https://github.com/babel/babel/pull/12331/files?file-filters%5B%5D=.js#diff-d69755d940c994561bcd6a6f7eff996d76922577a5dbfd097d12f2d245a8b11eR165

**Comment by nicolo-ribaudo** [comment]
Not directly related to this bug, but you can probably remove this custom plugin by doing something like https://github.com/storybookjs/storybook/pull/13055 (so that Babel already inject imports to the correct `core-js` path).

**Pull request merged**
