### PR TITLE
chore: outdated version notify when commenting `/version`

### PR DESCRIPTION
**Pull request by ycjcl868**
评论  `/version` 触发版本检测

##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/umi/ISSUE_URL

### CODE REVIEW

**Comment by sorrycc** [comment]
手动检测吧，有不少依赖是不升的，会有很多冗余信息。

**Comment by ycjcl868** [comment]
> 手动检测吧，有不少依赖是不升的，会有很多冗余信息。

只做检测，不自动升级

**Review by sorrycc — APPROVED** [review]

**Pull request merged**
