### PR TITLE
feat: support vue

### PR DESCRIPTION
**Pull request by sorrycc**
##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/umi/ISSUE_URL

-----
[View rendered packages/plugin-vue/README.md](https://github.com/umijs/umi/blob/feat/support-vue/packages/plugin-vue/README.md)
[View rendered packages/renderer-vue/README.md](https://github.com/umijs/umi/blob/feat/support-vue/packages/renderer-vue/README.md)

### CODE REVIEW

**Comment by ycjcl868** [comment]
👍

**Comment by xiaohuoni** [comment]
🥱

**Comment by meloseven** [comment]
☕️

**Comment by meloseven** [comment]
If exportStatic is set, the router uses react-router-config in createRouteMiddleware.ts for matching.If support vue, this need to be modified.

**Comment by liujiayii** [comment]
这个神奇的pr真的会发布吗？
image

**Pull request closed without merging**
