### PR TITLE
bug(history): mock dynamic binding as default export not following es spec

### LINKED ISSUE #4144: router.push 相同的 地址 界面不能重新加载数据
我当前的地址为：
http://localhost:8000/system/member/update/1

我用router.push('/system/member/update/2')
也就是加载ID为2的数据。。
但是界面没变，。也没请求后端数据。。但是地址栏变成了 /system/member/update/2。。
但是内容还是1 的。。

### LINKED ISSUE #4159: router.push后，地址栏变了，但是页面并没有变
import router from ‘umi/router’
*****
router.push("/home")
******
操作后this.props.children.props.location.pathname  还是上一个路由的名称，没有变

- **Umi Version**:2.13.6
- **Node Version**:12.14.1
- **Platform**:Windows 10

### PR DESCRIPTION
**Pull request by kuitos**
##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close #4159
- close #4144
- close #4172

---
This change is [Reviewable](https://reviewable.io/reviews/umijs/umi/4162)

### CODE REVIEW

**Comment by kuitos** [comment]
本地跑了下提交前的 2.x 分支，ci 也是挂的， @ycjcl868 看下？

**Comment by sorrycc** [comment]
merge 下 2.x 分支，ci 修复了。

**Comment by kuitos** [comment]
合并了 ci 还是挂的~ 本地切到 2.x 分支试了下也是跑不通，我提个 typo 的 pr 试试

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/pull/4175
陈帅 的 PR ci 好像没问题。

**Comment by kuitos** [comment]
嗯我得看一下

**Comment by sorrycc** [comment]
合了跑跑看。

**Pull request merged**
