### PR TITLE
feat: add 404 plugin

### PR DESCRIPTION
**Pull request by xiaohuoni**
##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change
增加约定式的 404 逻辑，文档里都有，这个功能应该是漏了。
没有实现 “umi dev 404 page” ，重复答疑次数太多了。（ dev 的时候，自定义的 404 页面无效，需要 build 之后才会生效。）

- any feature?
- close https://github.com/umijs/umi/issues/5092

### CODE REVIEW

**Comment by Mu-xue** [comment]
哪个版本才会修复这个问题？

**Comment by xiaohuoni** [comment]
@sorrycc cc

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/5081

**Comment by 134355** [comment]
这个太坑了，
`[
    {
      path: '/',
      breadcrumbName: '首页',
      component: '@/layouts/baseLayout/index',
      routes: [
        {
          path: '/',
          component: '@/pages/index',
          title: 'index'
        },
        {
          path: './2',
          component: '@/pages/index2',
          title: 'index'
        },
        {
          title: '404',
          path: '/404',
          breadcrumbName: '404',
          component: '@/pages/404'
        },
      ]
    },`
url: /212
这样就可以了，但是只是一层啊
[
    {
      path: '/',
      breadcrumbName: '首页',
      component: '@/layouts/baseLayout/index',
      routes: [
        {
          path: '/1',
          component: '@/pages/index',
          title: 'index',
          routes: [
            {
              path: './3',
              component: '@/pages/index2',
              title: 'index'
            },
          ]
        },
        {
          path: './2',
          component: '@/pages/index2',
          title: 'index'
        },
      ]
    },
    {
      title: '404',
      path: '/404',
      breadcrumbName: '404',
      component: '@/pages/404'
    },
  ]
url: /13/32
这样又不行了，

所以应该是下面这样的才对
我管你是一层二层三层路由
`[
    {
      path: '/',
      breadcrumbName: '首页',
      component: '@/layouts/baseLayout/index',
      routes: [
        {
          path: '/',
          component: '@/pages/index',
          title: 'index'
        },
        {
          path: './2',
          component: '@/pages/index2',
          title: 'index'
        },
      ]
    },
    {
      title: '404',
      path: '/404',
      breadcrumbName: '404',
      component: '@/pages/404'
    },
  ]`

**Pull request closed without merging**
