### PR TITLE
dep: webpack-bundle-analyzer -> umi-webpack-bundle-analyzer

### PR DESCRIPTION
**Pull request by RaoHai**
##### Checklist
- [x] `npm test` passes
- [x] commit message follows commit guidelines

##### Description of change
- feat: change `webpack-bundle-analyzer` to self-maintained libray `umi-plugin-bundle-analyzer`, which is full compatible to previous and implements more features for analyze.

### CODE REVIEW

**Comment by RaoHai** [comment]
@sorrycc 
@ikobe

**Comment by ikobe** [comment]
+1

**Comment by sorrycc** [comment]
好了后再把标题里的 `[WIP]` 去掉吧。

**Comment by RaoHai** [comment]
> 好了后再把标题里的 `[WIP]` 去掉吧。

done

**Comment by RaoHai** [comment]
@sorrycc

**Pull request merged**
