### PR TITLE
fix: sort route

### PR DESCRIPTION
**Pull request by xiaohuoni**
##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/umi/issues/4288

### CODE REVIEW

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/blob/1be095aaf07e39a6bfc226b02e9e937846c5f465/packages/core/src/Route/getConventionalRoutes.ts#L135
约定式路由的排序在这里做，估计有 BUG。

**Comment by xiaohuoni** [comment]
> https://github.com/umijs/umi/blob/1be095aaf07e39a6bfc226b02e9e937846c5f465/packages/core/src/Route/getConventionalRoutes.ts#L135
> 
> 
> 约定式路由的排序在这里做，估计漏了他的这个场景。

我觉得在统一出口的地方处理会比较合适吧？有可能配置里面写的顺序也有问题的情况，可以自动矫正一下

**Comment by xiaohuoni** [comment]
@sorrycc 改了

**Comment by sorrycc** [comment]
修地不对，我来修下。

**Pull request closed without merging**
