### PR TITLE
fix: change externals schema

### PR DESCRIPTION
**Pull request by xiaohuoni**
##### Checklist

- [x] `npm test` passes
- [ ] tests are included
- [x] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

Close: https://github.com/umijs/umi/issues/5170

### CODE REVIEW

**Comment by xiaohuoni** [comment]
image

**Comment by xiaohuoni** [comment]
image

**Comment by ycjcl868** [comment]
可以用 https://hapi.dev/module/joi/tester/ 这个测下

**Comment by sorrycc** [comment]
为啥要 array? object 不够用？

**Comment by xiaohuoni** [comment]
> 可以用 https://hapi.dev/module/joi/tester/ 这个测下

404

**Comment by xiaohuoni** [comment]
> 为啥要 array? object 不够用？

webpack 本身支持这些用法，既然是透传参数，感觉保持官方用法最好。终于为啥不够用。看相关 issues。应该是有需求。

**Comment by RaoHai** [comment]
LGTM.
但是就“够用”来说 object 在大多数场景里肯定是够了。。

**Comment by xiaohuoni** [comment]
@sorrycc 这个能合并吗？

**Comment by sorrycc** [comment]
不合了吧，不必追求全量 webpack，太灵活反而会给之后的辅助工具带来困难。

**Comment by KrishnaPG** [comment]
Is this merged?

The array configuration is required to support `regEx` and `functional` style of externals. For example, refer to this [externals combining-syntaxes](https://webpack.js.org/configuration/externals/#combining-syntaxes)

Currently it is not possible with UMI to achieve the below (which is fully supported by webpack):
````
  externals: [
    {
      react: 'react',
    },
    // Regex
    /^(jquery|\$)$/i
  ]

````

**RegEx** is needed when there are many sub-folders that need to be externalized, such as:
````
@ant-design/pro-card
@ant-design/pro-descriptions
@ant-design/pro-field 
...
````

**Comment by fxxjdedd** [comment]
@sorrycc 

https://github.com/ant-design/ant-design-pro/issues/7403

We can not fix this issue without a Regx externals schema. Please merge it. 🙏

**Pull request closed without merging**
