### PR TITLE
refactor: support Basic UI extend using modifyBasicUI for Bigfish

### PR DESCRIPTION
**Pull request by ycjcl868**
上层框架扩展 (Bigfish) 使用：

```js
  // 注入 UmiUI 扩展 UI 及 Service
  process.env.BASIC_UI_PATH = require.resolve('@alipay/bigfish-ui/dist/index.umd.js');
  process.env.BASIC_CONFIG_PATH = require.resolve('@alipay/bigfish-ui');
```

`umiUI/ui.tsx`

```tsx
import React from 'react';
import { IUiApi } from 'umi-types';
import Logo from './components/logo';
import CreateButton from './components/createButton';

/**
 * Bigfish Compact Config
 */
export default (api: IUiApi) => {
  api.modifyBasicUI({
    name: 'Bigfish',
    logo: <Logo />,
    logo_remote: '...',
    feedback: {
      src: '...',
      width: 150,
      height: 200,
    },
    helpDoc: '',
    'create.project.button': <CreateButton api={api} />,
  });
};

```

- [x] Basic UI 扩展 API `modifyBasicUI`
- [ ]  插件层扩展

##### Checklist

- [x] `npm test` passes
- [x] documentation is changed or added
- [x] tests are included
- [x] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/umi/ISSUE_URL

### CODE REVIEW

**Comment by sorrycc** [comment]
Bigfish 层怎么用？

**Comment by ikobe** [comment]
step form 似乎也要扩展

**Comment by ycjcl868** [comment]
看需要扩展多少，我还在封装

**Comment by ycjcl868** [comment]
可以合了

**Comment by ycjcl868** [comment]
补下用例

**Pull request merged**
