### PR TITLE
feat: add env CLEAR_OUTPUT

### PR DESCRIPTION
**Pull request by ulivz**
##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

- any feature?

Add a new env `UMI_DO_NOT_CLEAN_OUTPUT` to make is possible to tell `build` process not to remove the dist files.

- close https://github.com/umijs/umi/issues/2448

### CODE REVIEW

**Comment by sorrycc** [comment]
按之前的环境变量约定，需要改成 `CLEAN_OUTPUT === 'none'` 时不清空。

**Comment by ulivz** [comment]
好的，我看了下之前的命名，好像都是用的 CLEAR，就先用 CLEAR_OUTPUT 了，文档也更新了。

**Comment by sorrycc** [comment]
ci 挂了。

**Comment by ulivz** [comment]
CI 过了，好像覆盖率不够 ... 这个要写单测吗？

**Comment by Tammeny** [comment]
这个具体怎么用？官方文档没看到有相关信息

**Pull request merged**
