### PR TITLE
feat: ui footer add  open editor 

### LINKED ISSUE #3688: [Feature Request] UMI UI 中前端早报分页问题
『查看更多』改成『展开所有』，点击后一次性打开所有。现在是超过 10 条信息，要点两次才能看完，体验不太好。

### PR DESCRIPTION
**Pull request by ycjcl868**
##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/umi/ISSUE_URL

Close #3688

-----
[View rendered docs/guide/faq.md](https://github.com/umijs/umi/blob/feat-ui-open-editor/docs/guide/faq.md)
[View rendered docs/zh/guide/faq.md](https://github.com/umijs/umi/blob/feat-ui-open-editor/docs/zh/guide/faq.md)

### CODE REVIEW

**Comment by sorrycc** [comment]
1. 截个图看下
2. 会不会太多地方了，加上这个有三个编辑器打开了

**Comment by ycjcl868** [comment]
image

**Comment by sorrycc** [comment]
如果下面有了，左上和右上的是否应该删掉？

**Comment by ycjcl868** [comment]
右上的可以删掉

**Comment by ycjcl868** [comment]
done

**Pull request merged**
