### PR TITLE
feat(css-loader): css modules default support camelCase convent

### PR DESCRIPTION
**Pull request by zthxxx**
##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

- any feature?
- css modules default support camelCase convent

```file.css
.icon-class-name {
}
```

```file.jsx
import styles from 'file.css'

styles.iconClassName
styles['icon-class-name']
```

ref: https://github.com/webpack-contrib/css-loader#localsconvention

### CODE REVIEW

**Comment by sorrycc** [comment]
这是 break change，不改了吧，要用 camelCase，样式也用 camelCase 组织。

**Comment by zthxxx** [comment]
@sorrycc 文档地址贴出来了，是兼容写法，结果一样

```js
.icon-class-name {
}

.iconClassName {
}

import styles from 'file.css'

styles.iconClassName
styles['icon-class-name']
```

**Comment by zthxxx** [comment]
@yutingzhao1991  麻烦看看这个 feature

**Comment by WangJi** [comment]
默认两者都兼容，挺好的啊，为啥关闭了？
> Class names will be camelized, the original class name will **not** to be removed from the locals

原className不会删除。

**Pull request closed without merging**
