### PR TITLE
chore: speed github ci faster

### PR DESCRIPTION
**Pull request by ycjcl868**
> npm ci is fast—in some cases, twice as fast as using npm i

Refs: 
- https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable
- https://stackoverflow.com/questions/58482655/what-is-the-closest-to-npm-ci-in-yarn

##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/umi/ISSUE_URL

### CODE REVIEW

**Comment by sorrycc** [comment]
image
和开启前没啥差异？

**Comment by ycjcl868** [comment]
> image
> 和开启前没啥差异？

因为 yarn.lock 没变更，所以走的是缓存，变更后执行  `yarn` 时就有差异了

**Comment by sorrycc** [comment]
这个 PR 里触发个变更试试效果。

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/runs/2242372243
有依赖变更也是 3m，如果没数据支撑，这个 PR 就关了。

**Pull request closed without merging**
