### PR TITLE
fix: g_initialData in windows

### LINKED ISSUE #2657: 2.8.0 core-js not found
run umi 2.8.0 command : umi build, got errors as follows:

$ umi build                                                                                                                    
Build completed in 0.442s                                                                                                      
                                                                                                                               
 ERROR  Failed to compile with 1 errors                                                                                        
                                                                                                                               
 error  in ./src/pages/.umi-production/umi.js                                                                                  
                                                                                                                               
Syntax Error: SyntaxError: project_path\ui\src\pages\.umi-production\umi.js: Bad character escape sequence (6:51)
                                                                                                                               
  4 | import React from 'react';                                                                                               
  5 | import ReactDOM from 'react-dom';                                                                                        
> 6 | import findRoute from 'project_path\ui\node_modules\_umi-build-dev@1.10.0@umi-build-dev\lib\findRoute.js'; 
    |                                                    ^                                                                     
  7 |                                                                                                                          
  8 |                                                                                                                          
  9 | // runtime plugins                                                                                                       
                                                                                                                               
                                                                                                                               
 @ multi ./src/pages/.umi-production/umi.js

### PR DESCRIPTION
**Pull request by lemol**
##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- close #2657
- complements #2660

### CODE REVIEW

**Comment by ycjcl868** [comment]
ci broken, could you please fix it?

**Comment by lemol** [comment]
Cannot understand why the CI fails. It happens on e2e tests while closing browser https://travis-ci.org/umijs/umi/jobs/548136396#L764
The same happens on master branch.

**Comment by lemol** [comment]
@ycjcl868, after a fix in mater branch, CI now passes.

**Comment by ycjcl868** [comment]
ok, ci is ok

**Pull request merged**
