### PR TITLE
Add an export store for data mock

### PR DESCRIPTION
**Pull request by arvinxx**

### CODE REVIEW

**Comment by sorrycc** [comment]
mock with `window.g_app._store`?

**Comment by arvinxx** [comment]
my mistake.
Not for  the mock but for unified request in Ant Design Pro. In the [request.js](https://github.com/ant-design/ant-design-pro/blob/master/src/utils/request.js#L4) it need get store from app.
So app need export a store to work for `request.js`. Like [this](https://github.com/ant-design/ant-design-pro/blob/master/src/index.js#L34)

**Comment by sorrycc** [comment]
DvaContainer is a tmp file, you should not import from it, I think `window.g_app._store` is better.

**Comment by arvinxx** [comment]
Yeah. And I close it.

**Pull request closed without merging**
