### PR TITLE
chore(lint): upgrade typescript eslint deps

### LINKED ISSUE #11564: [Bug] typescript@5.1.6升级到typescript@5.2.2，eslint错误
## What happens?

typescript@5.1.6升级到typescript@5.2.2，eslint错误
image
ESLint: Parsing error: DeprecationError: originalkeyword Kind since v5.0.0 and can no longer be used. Use identifierToKeywordKind(identifier)' instead

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

typescript@5.1.6升级到typescript@5.2.2 可复现
typescript 里相关代码：https://github.com/microsoft/TypeScript/blob/main/src/deprecatedCompat/5.0/identifierProperties.ts
我猜eslint的相关包应该要升级才能支持

## How To Reproduce

typescript@5.1.6升级到typescript@5.2.2 后，webstorm 工具自动报ESLint错，typescript@5.1.6版本正常

## Context

- **Umi Version**:4.0.78
- **Node Version**: 16.14.0
- **Platform**:windows 10

### PR DESCRIPTION
**Pull request by fz6m**
close #11564

### CODE REVIEW

**Comment by hanzebang** [comment]
+1

**Review by PeachScript — COMMENTED** [review]
升 major 应该会有 Breaking Change，要么升级到 5.x 的最新版，看代码也兼容了 TypeScript 5.0

v6 Changelog 的 Breaking Change 在这里：https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/#user-facing-breaking-changes

**Comment by fz6m** [comment]
好的，已采用 v5 最新版本，经验证可以在 TS v5.2 下运行。

**Review by PeachScript — APPROVED** [review]
+1

**Comment by andyFang94** [comment]
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0

YOUR TYPESCRIPT VERSION: 5.2.2

Please only submit bug reports when using the officially supported version.      

=============

@fz6m 是不是还得继续升级

**Pull request merged**
