### PR TITLE
fix: .env.local should take precedence over .env

### PR DESCRIPTION
**Pull request by yingzhiji**
##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/umi/ISSUE_URL

### CODE REVIEW

**Comment by yingzhiji** [comment]
目前的文件加载顺序有问题，.env.local 应该比 .env 优先，为了防止不兼容，单独提交。

**Comment by yingzhiji** [comment]
#6303

**Comment by sorrycc** [comment]
原来的没问题，后者会覆盖前者，所以 local 放后面其实优先级更高。

**Comment by yingzhiji** [comment]
image
loadDotEnv 里是已经有的变量就不赋值 @sorrycc

**Pull request merged**
