### PR TITLE
feat: support less themeVars

### PR DESCRIPTION
**Pull request by ycjcl868**
##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/umi/ISSUE_URL

### CODE REVIEW

**Comment by ycjcl868** [comment]
这个 code format 还以为改动了很多文件 🙈，

**Comment by ycjcl868** [comment]
感觉 lib 很多配置要手动加，不能充分用到 umi 的配置项

**Comment by sorrycc** [comment]
这个 theme 只给 doc 用，还是 lib build 也能用？

**Comment by ycjcl868** [comment]
theme 不需要了，另一个需要，Bigfish 里 issue 讨论。先 Close 了

**Pull request closed without merging**
