### PR TITLE
fix: IPresetOrPlugin type definition

### PR DESCRIPTION
**Pull request by vdfor**
##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/umi/ISSUE_URL

If use two separate instances of a babel plugin, they need separate names.

e.g.

```ts
{
  extraBabelPlugins: [
    [
      'import',
      { libraryName: 'package-a', libraryDirectory: '', camel2DashComponentName: false },
      'package-a',
    ],
    [
      'import',
      { libraryName: 'package-b', libraryDirectory: '', camel2DashComponentName: false },
      'package-b',
    ]
  ]
}
```

### CODE REVIEW

**Comment by sorrycc** [comment]
啥时候是这么用的？我想不起来了。`[string, any, string?]`

**Comment by vdfor** [comment]
> 啥时候是这么用的？我想不起来了。`[string, any, string?]`

添加同一插件的多个实例时，需要第三个设置别名，比如 `babel-plugin-import` 同时配置 `lodash` 与 `material-ui`，需要配置如下：

```json
// .babelrc
"plugins": [
  ["import", { "libraryName": "lodash", "libraryDirectory": "","camel2DashComponentName":false}, "lodash"],
  ["import", { "libraryName": "@material-ui/core", "libraryDirectory": "components","camel2DashComponentName": false, }, "@material-ui/core"]
]
```

https://github.com/ant-design/babel-plugin-import

**Comment by sorrycc** [comment]
那需要区分下 umi 的和 babel 的。

**Comment by sorrycc** [comment]
extraBabelPresets 也要改下。

**Pull request merged**
