### PR TITLE
feat: independent hd plugin.

### PR DESCRIPTION
**Pull request by ulivz**
## Summary

`umi-plugin-hd` doesn't rely on any react-related stuffs and it's better to separate it from `umi-plugin-react` so that other  framework users (e.g. vue) will benefit from it.

### CODE REVIEW

**Comment by xiaohuoni** [comment]
It was a independent. I thought it was a perfect hd.Quite excited.

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-hd

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-hd 这个项目是做什么的？还有umijs/umi-plugin-locals？

**Comment by sorrycc** [comment]
@xiaohuoni umijs/umi-hd 是内部 @写轮 同学写的实现 hd 效果的 js，umijs/umi-plugin-locale 应该没有用，可以删了。

**Pull request merged**
