### PR TITLE
chore(postcss): add test cases for postcss-preset-env

### PR DESCRIPTION
**Pull request by ycjcl868**
Refs: https://github.com/umijs/umi/pull/6297, https://github.com/csstools/postcss-preset-env/issues/191

`postcss-preset-env` can't upgrade into PostCSS 8, but umi used the  stage 3 `features` of `postcss-preset-env`, so we could only add `postcss 8` and `postcss-preset-env` together.

##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/umi/ISSUE_URL

### CODE REVIEW

**Comment by ycjcl868** [comment]
https://github.com/csstools/postcss-preset-env/blob/d7652b1e6196e8f55bf3f0aac4ac090fec7ed54e/src/postcss.js#L104-L108

**Comment by sorrycc** [comment]
用例没过。

**Comment by ycjcl868** [comment]
> 用例没过。

Fixed

**Comment by sorrycc** [comment]
查了下 stage 3 是有含义的，会应用 cssdb 里相关的 feature，直接删了会有影响吗？

**Comment by LeoHuiyi** [comment]
如果之前有用到postcss-preset-env别的功能，这样删除会breakchange的

**Comment by ycjcl868** [comment]
> 如果之前有用到postcss-preset-env别的功能，这样删除会breakchange的

加回来了

**Comment by ycjcl868** [comment]
先 Revert, postcss 8 暂升不动

**Pull request closed without merging**
