### PR TITLE
修改错别字

### PR DESCRIPTION
**Pull request by huangdeyin**
修改错别字"隐"至"映"

##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/umi/ISSUE_URL

-----
[View rendered 文档/配置/README.zh-CN.md](https://github.com/huangdeyin/umi/blob/patch-1/文档/配置/README.zh-CN.md)

### CODE REVIEW

**Comment by PeachScript** [comment]
@huangdeyin 为什么文件的路径修改了…

**Comment by huangdeyin** [comment]
@PeachScript 。。。我用手机修改的，文件路径自动翻译了，导致提交的路径变了

**Comment by PeachScript** [comment]
@huangdeyin  原来如此，一开始还以为是文档的编辑链接有问题 😂

**Comment by huangdeyin** [comment]
最近在学umijs，看到有错别字，就提了一下...下次注意o(╥﹏╥)o

**Pull request merged**
