### PR TITLE
fix: Fix qiankun route match

### PR DESCRIPTION
**Pull request by iamkun**
To keep the same logic with umi 3.x qiankun plugin

ref: https://github.com/umijs/plugins/blob/master/packages/plugin-qiankun/src/master/getMicroAppRouteComponent.ts.tpl#L27

### CODE REVIEW

**Review by kuitos — APPROVED** [review]
LGTM

**Review by sorrycc — APPROVED** [review]

**Comment by DevilMayDead** [comment]
@sorrycc useMatch获取不到路由，导致useContext错误

**Comment by kuitos** [comment]
> 
怎么复现？

**Comment by DevilMayDead** [comment]
> 怎么复现？

export function patchClientRoutes({routes}: any) {
  routes[0].children.forEach((item: any, index: number) => {
    if (item.microApp) {
      // console.log(item)
      console.log(item,item.microAppProps?.baseName)
      routes[0].children[index].element = getMicroAppRouteComponent({
        appName: item.microApp,
        base: item.microAppProps?.baseName || '/',
        routePath: item.path,
        masterHistoryType: item.microAppProps?.hisory || 'browser',
        // routeProps: {
        //   errorBoundary: (error: any) => <>error</>
        // }
      })()
    }
  })
}

**Pull request merged**
